// =============================================================================
// MediaTypes.ts
//
// Purpose:
// Central location for types shared by Media Player and Signage.
//
// This file contains NO business logic.
// =============================================================================

// =====================
// BASIC MEDIA TYPES
// =====================

export type MediaFrequency = "Evergreen" | "Daily" | "LTO";
export type MediaType = "video" | "images";

// ====================================
// MEDIA PLAYER LOCAL PLAYLIST ITEM
// ====================================

export interface PlaylistItems {
  mediaUuid: string; // UUID from media_library
  key: string; // S3 object key (Example: Global/01_Staging_Video_Landscape.mp4)
  type: MediaType; // Media type determined by backend
  url: string; // Original Cloudfront URL
  localUri: string; // Local file: //URI on the TV
  fileName: string; // Display filename
  frequency: MediaFrequency; // Scheduling rule
  /**
   * Scheduling start.
   *
   * Daily:
   *   date portion is ignored by playback logic.
   *
   * LTO:
   *   full date and time are used.
   */
  startDatetime: string | null;
  endDatetime: string | null; // Scheduling end
}

// ====================================
// BACKEND MEDIA PLAYER CONFIGURATION
// ====================================

export interface MediaPlayerConfigItem {
  video_uuid: string;
  video_name: string;
  object_key: string;
  type: MediaType;
  screen_type: "Media Player";
  batch_num: number;
  tier: string;
  orientation: "Landscape" | "Portrait";

  start_datetime: string | null;
  end_datetime: string | null;

  frequency: MediaFrequency;

  url: string; // Cloudfront URL generated by backend
}

export interface MediaPlayerConfigResponse {
  success: boolean;

  outlet: {
    outlet_id: string;
    outlet_name: string;
    tier: string;
  };

  etag: string;
  screens: MediaPlayerConfigItem[];
}

// ============================
// MEDIA PLAYER LOGIN REQUEST
// ============================

export interface MediaPlayerLoginPayload {
  outletId: string;
  batchNumber: number;
  tier: string;
  orientation: "Landscape" | "Portrait";
}

// =======================
// MEDIA PLAYER VERSION
// =======================

export interface MediaPlayerVersion {
  etag: string;
  itemCount: number;
}

// ================
// DOWNLOAD STATE
// ================

export interface MediaDownloadProgress {
  completed: number;
  total: number;
  currentFile: string;
}

export type MediaDownloadStatus = "downloading" | "ready" | "error";

export interface MediaDownloadState {
  status: MediaDownloadStatus;
  completed: number;
  total: number;
  currentFile: string;
  error?: string;
}

// ==================
// PLAYLIST REFRESH
// ==================

export interface PlaylistRefreshResult {
  changed: boolean;
  playlist: PlaylistItems[];
  oldFilesToDelete: string[];
  etag: string | null;
}

// ===============
// SIGNAGE
// ===============

export interface SignageVersion {
  etag: string | null;
  itemCount: number;
}

export interface PreparedSignageVideo {
  videoUri: string; // Original Cloudfront URL
  localUri: string; // Local file:// URI
  key: string; // S3 object key
  rotate?: boolean;
  sizeMb?: number;
  optimized?: boolean;
}

export interface SignageItem {
  videoURI: string;
  key?: string;
  rotate?: boolean;
  sizeMb?: number;
  optimized?: boolean;
}

// =========================
// LOCAL PLAYLIST METADATA
// =========================

export interface PlaylistMeta {
  outletId: string;
  batchNumber: number;
  tier: string;
  orientation: "Landscape" | "Portrait";
  etag: string;
  items: PlaylistItems[];
}

export interface SignageMeta {
  etag: string;
  outletId: string;
  items: PreparedSignageVideo[];
}
